# Copyright 2004-present, Facebook. All Rights Reserved.
# Generated by Django 3.1.4 on 2021-03-04 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('COMMERCE_ACCOUNT', 'commerce account')], default='COMMERCE_ACCOUNT', max_length=30)),
                ('event', models.CharField(choices=[('setup_status', 'setup status')], max_length=50)),
                ('time_sent', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('time_received', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('raw_notification_data', models.TextField(blank=True, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.store')),
            ],
        ),
    ]
