# Copyright 2004-present, Facebook. All Rights Reserved.
# Generated by Django 3.1.4 on 2021-03-04 19:56

import core.models.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_business_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=core.models.utils.datetime_utc_now_with_tz)),
                ('historical_catalogs', models.TextField(blank=True, default='')),
                ('catalog_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog', to='catalog.catalog')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.store')),
                ('shipping', models.TextField(blank=True, null=True)),
                ('tax', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('payout', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantToStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('merchant', 'name'), name='unique_store_name_for_merchant'),
        ),
    ]
