# Copyright 2004-present, Facebook. All Rights Reserved.
# Generated by Django 3.1.4 on 2021-03-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_group_type', to='catalog.productgroup'),
        ),
        migrations.AddField(
            model_name='collection',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
        migrations.AddField(
            model_name='productgroupitem',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productgroup'),
        ),
        migrations.AddConstraint(
            model_name='productgroup',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_product_group_name_for_store'),
        ),
        migrations.AddField(
            model_name='catalogitemgroup',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog'),
        ),
    ]
