# Copyright 2004-present, Facebook. All Rights Reserved.
#!/usr/bin/env python3

"""
Django settings for cp_reference project.
Generated by 'django-admin startproject' using Django 3.1.3.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

# @lint-ignore FBCODEBUCKFORMAT
import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

APP_ID = os.getenv("FB_APP_ID")
APP_NAME = os.getenv("APP_NAME")

DOMAIN = os.getenv("FB_EXTENSION_REDIRECT_DOMAIN")

REDIRECT_URI = str(DOMAIN) + "/callback"

APP_SECRET = os.getenv("FB_APP_SECRET")

API_VERSION = os.getenv("GRAPH_API_VERSION", "v9.0")

BASE_API_URL = "https://graph.facebook.com/"

GET_ACCESS_TOKEN_URL = "https://graph.facebook.com/{}/oauth/access_token?client_id={}&redirect_uri={}&client_secret={}&code=".format(
    API_VERSION, APP_ID, REDIRECT_URI, APP_SECRET
)

FBE_MANAGEMENT_VIEW_REDIRECT = "https://www.facebook.com/facebook_business_extension/management/?app_id={}&external_business_id=".format(
    APP_ID
)

FBE_ONBOARDING_URL = "https://facebook.com/dialog/oauth?client_id={}&display=page&redirect_uri={}&response_type=code&scope={}&state={}&extras={}"

FBE_INFO_API_URL = "https://graph.facebook.com/"+API_VERSION+"/fbe_business/fbe_installs?fbe_external_business_id={}&access_token={}"

SYSTEM_USER_TOKEN_API_URL = "https://graph.facebook.com/"+API_VERSION+"/{}/access_token"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django_celery_beat",
    "django_celery_results",

    "order",
    "catalog",
    "member",
    "shop",
    "core",
    "fb_metadata",
    "webhook",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.app_name",
                "config.context_processors.allStoresContext",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

FIXTURE_DIRS = ("/fixtures/",)


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static_files")

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static/")]

CELERY_BROKER_URL = os.getenv("REDIS_URL")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = LOGIN_URL
GENERATE_PRODUCT_LINK = True
