# Copyright 2004-present, Facebook. All Rights Reserved.
# Generated by Django 3.1.4 on 2021-03-04 19:56

import core.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20210304_1956'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('addr', models.TextField(blank=True, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_order_id', models.CharField(default=None, max_length=50, null=True)),
                ('order_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CONFIRMED_ORDER', 'Confirmed Order'), ('FB_CREATED', 'FB Created'), ('IN_PROGRESS', 'In progress')], default='FB_CREATED', max_length=15)),
                ('order_refund_state', models.CharField(choices=[('FULLY_REFUNDED', 'Fully refunded'), ('NO_REFUNDS', 'No refunds'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='NO_REFUNDS', max_length=18)),
                ('created', models.DateTimeField(blank=True, default=core.models.utils.datetime_utc_now_with_tz)),
                ('last_updated', models.DateTimeField(blank=True, default=core.models.utils.datetime_utc_now_with_tz)),
                ('ship_by_date', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('ARS', 'Argentine Peso'), ('AUD', 'Australian Dollar'), ('BDT', 'Bangladeshi Taka'), ('BOB', 'Bolivian Boliviano'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CLP', 'Chilean Peso'), ('CNY', 'Chinese Yuan'), ('COP', 'Colombian Peso'), ('CRC', 'Costa Rican Colon'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('EGP', 'Egyptian Pounds'), ('EUR', 'Euro'), ('GTQ', 'Guatemalan Quetza'), ('HNL', 'Honduran Lempira'), ('HKD', 'Hong Kong Dollar'), ('HUF', 'Hungarian Forint'), ('ISK', 'Iceland Krona'), ('INR', 'Indian Rupee'), ('IDR', 'Indonesian Rupiah'), ('ILS', 'Israeli New Shekel'), ('JPY', 'Japanese Yen'), ('KES', 'Kenyan Shilling'), ('KRW', 'Korean Won'), ('MOP', 'Macau Patacas'), ('MYR', 'Malaysian Ringgit'), ('MXN', 'Mexican Peso'), ('NZD', 'New Zealand Dollar'), ('NIO', 'Nicaraguan Cordoba'), ('NGN', 'Nigerian Naira'), ('NOK', 'Norwegian Krone'), ('PKR', 'Pakistani Rupee'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Nuevo Sol'), ('PHP', 'Philippine Peso'), ('PLN', 'Polish Zloty'), ('QAR', 'Qatari Rials'), ('RON', 'Romanian Leu'), ('RUB', 'Russian Ruble'), ('SAR', 'Saudi Arabian Riyal'), ('SGD', 'Singapore Dollar'), ('ZAR', 'South African Rand'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('TWD', 'Taiwan Dollar'), ('THB', 'Thai Baht'), ('TRY', 'Turkish Lira'), ('AED', 'Uae Dirham'), ('USD', 'United States Dollar'), ('UYU', 'Uruguay Peso'), ('VEF', 'Venezuelan Bolivar'), ('VND', 'Vietnamese Dong')], default='USD', max_length=3)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('order_fulfillment_state', models.CharField(choices=[('FULLY_FULFILLED', 'Fully fulfilled'), ('NO_FULFILLMENT', 'No fulfillment'), ('PARTIALLY_FULFILLED', 'Partially fulfilled')], default='NO_FULFILLMENT', max_length=19)),
                ('order_cancellation_state', models.CharField(choices=[('FULLY_CANCELLED', 'Fully cancelled'), ('NO_CANCELLATION', 'No cancellation'), ('PARTIALLY_CANCELLED', 'Partially cancelled')], default='NO_CANCELLATION', max_length=19)),
                ('missing_items', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.customer')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
